services:
  - type: web
    name: whisper-transcriber
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
      - key: CACHE_TYPE
        value: redis
      - key: CACHE_REDIS_URL
      - key: REDIS_URL
    plan: free
